language: go
go:
  - "1.11"
  - "1.12"
  - "master"
matrix:
  allow_failures:
    - go: "master"
script:
  - go test -v -race -cpu=1,2,4 -bench . -benchmem ./...
  - go test -v -tags binary_log -race -cpu=1,2,4 -bench . -benchmem ./...