// Code generated by mockery v2.9.4. DO NOT EDIT.

package easylog

import mock "github.com/stretchr/testify/mock"

// MockFilter is an autogenerated mock type for the IFilter type
type MockFilter struct {
	mock.Mock
}

// Filter provides a mock function with given fields: _a0
func (_m *MockFilter) Filter(_a0 *Event) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*Event) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
