// Code generated by mockery v2.9.4. DO NOT EDIT.

package easylog

import mock "github.com/stretchr/testify/mock"

// MockHandler is an autogenerated mock type for the IHandler type
type MockHandler struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MockHandler) Close() {
	_m.Called()
}

// Flush provides a mock function with given fields:
func (_m *MockHandler) Flush() {
	_m.Called()
}

// Handle provides a mock function with given fields: _a0
func (_m *MockHandler) Handle(_a0 *Event) {
	_m.Called(_a0)
}
